# # ques1
# a1  = input("enter name of  fruits1: \n:")
# a2  = input("enter name of  fruits2: \n:")
# a3  = input("enter name of  fruits3: \n:")
# a4  = input("enter name of  fruits4: \n:")
# a5  = input("enter name of  fruits5: \n:")
# a6  = input("enter name of  fruits6: \n:")
# a7  = input("enter name of  fruits7: \n:")
# MyFruitList = [a1, a2 ,a3 , a4, a5 , a6 ,a7] 
# print(MyFruitList)

# # ques 2
# marks1  = input("enter the marks of students: \n:")
# marks2  = input("enter the marks of students: \n:")
# marks3  = input("enter the marks of students: \n:")
# marks4  = input("enter the marks of students: \n:")
# marks5  = input("enter the marks of students: \n:")
# marks6  = input("enter the marks of students: \n:")
# marks7  = input("enter the marks of students: \n:")
# studentMarks = [marks1, marks2, marks3 , marks4 , marks5, marks6, marks7]
# studentMarks.sort()
# print(studentMarks)

#ques 3

# Tupple = (7, 0, 8, 0, 0, 4 )
# x= Tupple.count(0)
# print(x)

a = "                  my name is nikhilbisht"
print(a.center(50,"0")) 
print(a.ljust(50,"0"))
print(a.rjust(50,"0"))
print(a.format())
print(a)
